config = dict(
    model_config=dict(
        model_name='SVC',
        parameters=dict(
            C=[1],
            kernel=['rbf'],
        ),
        n_jobs=-1,
    ),
    data_config=dict(
        random_seed=1,
        batch_size_train=64,
        batch_size_test=64,
        num_workers=0,
        epochs=100,
        test=dict(
            metrics=['accuracy', 'precision', 'recall', 'f1_score', 'confusion'],
            metric_options=dict(
                topk=(1,),
                thrs=None,
                average_mode='macro'
            ),
        ),
    ),
    optimizer_config=dict(
        type='SGD',
        lr=0.01,
        momentum=0.5,
        weight_decay=1e-4,
    ),
)
